- group:
    name: "{{ item }}"
  with_items:
  - dork
  - docker

- user:
    name: "{{ admin_name }}"
    groups: dork,docker
    append: yes
    generate_ssh_key: yes


- name: add dork user to sudoers
  lineinfile:
    line: "{{ admin_name }} ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers

- authorized_key:
    key: "{{ item }}"
    user: "{{ admin_name }}"
  with_items: admin_ssh_keys

- copy:
    src: ssh-config.sh
    dest: /etc/profile.d/ssh-config.sh

- file:
    path: /home/{{ admin_name }}/.ssh/config.d
    owner: "{{ admin_name }}"
    group: "{{ admin_name }}"
    state: directory

- copy:
    src: ssh-config
    owner: "{{ admin_name }}"
    group: "{{ admin_name }}"
    dest: /home/{{ admin_name }}/.ssh/config.d/dork.conf
